apiVersion: v1
kind: Namespace
metadata:
  name: pub-sub-source
  labels:
    istio-injection: enabled
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pub-sub-source-sa
  namespace: pub-sub-source